# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 1
  - name: Teams
    url: '/teams'
    weight: 20
  - name: About Us
    url: '/about'
    weight: 10
    identifier: about
  - name: Mission and Core Values
    url: '/about/mission'
    weight: 10
    parent: about
  - name: Team Members
    url: '/about/members'
    weight: 10
    parent: about
  - name: Sponsors
    url: '/about/sponsors'
    weight: 10
    parent: about
  - name: Blog
    url: '/post'
    weight: 30
  - name: For Team Members
    url: '/info'
    weight: 60
