# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 1
  - name: Gallery
    url: '/gallery'
    weight: 20
  - name: About
    url: '/about'
    weight: 10
    identifier: about
  - name: FIRST®
    url: '/about/first/'
    weight: 11
    parent: about
  - name: Mission and Core Values
    url: '/about/mission/'
    weight: 12
    parent: about
  - name: Team Members
    url: '/about/members/'
    weight: 13
    parent: about
  - name: Sponsors
    url: '/about/sponsors/'
    weight: 14
    parent: about
  - name: Blog
    url: '/post'
    weight: 30
    identifier: blog
  - name: Robophins - 3216
    url: '/post/robophins/'
    weight: 10
    parent: blog
  - name: Young Droids - 15659
    url: '/post/young-droids/'
    weight: 20
    parent: blog
  - name: For Team Members
    url: '/info/'
    weight: 60
